/* These are the MEP ROLES for pg_id=20, i.e. EPP-ED */

--set echo on


/* 
***************************************************



**************************************************
*/



/* Chair */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20001		
,20		
)
;



/*********************************************/


/*  Members **********************************/

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20002	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20003	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20011	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20012	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20013	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20014	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20015	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20016	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20017	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20018	
,80		
)
;






insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20019	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20020	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20021	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20022	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20023	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20024	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20025	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20026	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20027	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20028	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20029	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20030	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20031	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20032	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20033	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20034	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20035	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20036	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20037	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20038	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20039	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20040	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20041	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20042	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20043	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20044	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20045	
,80		
)
;






insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20046	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20047	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20048	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20049	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20050	
,80		
)
;






insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20051	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20052	
,80		
)
;







insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20053	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20054	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20055	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20056	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20057	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20058	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20059	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20060	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20061	
,80		
)
;





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20062	
,80		
)
;






insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20063	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20064	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20065	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20066	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20067	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20068	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20069	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20070	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20071	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20072	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20073	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20074	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20075	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20076	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20077	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20078	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20079	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20080	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20081	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20082	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20083	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20084	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20085	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20086	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20087	
,80		
)
;





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20088	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20089	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20090	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20091	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20092	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20093	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20094	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20095	
,80		
)
;





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20096	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20097	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20098	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20099	
,80		
)
;






insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20100	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20101	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20102	
,80		
)
;







insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20103	
,80		
)
;








insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20104	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20105	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20106	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20107	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20108	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20109	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20110	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20111	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20112	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20113	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20114	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20115	
,80		
)
;






insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20116	
,80		
)
;








insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20117	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20118	
,80		
)
;





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20119	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20120	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20121	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20122	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20123	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20124	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20125	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20126	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20127	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20128	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20129	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20130	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20131	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20132	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20133	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20134	
,80		
)
;





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20135	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20136	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20137	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20138	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20139	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20140	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20141	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20142	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20143	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20144	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20145	
,80		
)
;







insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20146	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20147	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20148	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20149	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20150	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20151	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20152	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20153	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20154	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20155	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20156	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20157	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20158	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20159	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20160	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20161	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20162	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20163	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20164	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20165	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20166	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20167	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20168	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20169	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20170	
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20171	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20172	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20173	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20174	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20175	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20176	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20177	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20178	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20179	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20180	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20181	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20182	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20183	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20184	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20185	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20186	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20187	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20188	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20189	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20190	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20191	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20192	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20193	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20194	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20195	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20196	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20197	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20198	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20199	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20200	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20201	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20202	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20203	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20204	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20205	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20206	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20207	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20208	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20209	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20210	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20211	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20212	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20213	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20214	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20215	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20216	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20217	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20218	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20219	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20220	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20221	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20222	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20223	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20224	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20225	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20226	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20227	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20228	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20229	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20230	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20231	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20232	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20233	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20234	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20235	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20236	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20237	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20238	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20239	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20240	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20241	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20242	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20243	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20244	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20245	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20246	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20247	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20248	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20249	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20250	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20251	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20252	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20253	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20254	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20255	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20256	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20257	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20258	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20259	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20260	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20261	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20262	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20263	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20264	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20265	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20266	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20267	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20268	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20269	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20270	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20271	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20272	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20273	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20274	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20275	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20276	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20277	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20278	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20279	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20280	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20281	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20282	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20283	
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20284	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20285	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20286	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20287	
,80		
)
;



/*********************************************/

/* Vice Presidents -- who make up the Parliament's Bureau  */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20004	
,50		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20005	
,50		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20006	
,50		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20007	
,50		
)
;



/*********************************************/


/*******QUAESTORS **********************/

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20008	
,60		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20009	
,60		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(20010	
,60		
)
;





/*********************************************/










/*********************************************/



COMMIT;


