--set echo on


/* These are the MEPS for pg_id=40, i.e. PES */


/* Chair */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40001		
,20		
);

/*********************************************/


/*  Members **********************************/



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40011		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40012		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40013		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40014		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40015		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40016		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40017		
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40018		
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40019		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40020		
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40021		
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40022		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40023		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40024		
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40025		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40026		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40027		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40028		
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40029		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40030		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40031	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40032	
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40033	
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40034	
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40035	
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40036	
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40037	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40038	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40039	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40040	
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40041	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40042		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40043		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40044		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40045		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40046		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40047		
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40048		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40049		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40050		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40051		
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40052		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40053		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40054		
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40055		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40056		
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40057		
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40058		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40059		
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40060		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40061		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40062		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40063		
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40064		
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40065		
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40066	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40067	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40068	
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40069	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40070	
,80		
);





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40071	
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40072	
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40073	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40074	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40075	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40076	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40077	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40078	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40079	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40080	
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40081	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40082	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40083	
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40084	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40085	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40086	
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40087	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40088	
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40089
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40090
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40091
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40092
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40093
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40094
,80		
);






insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40095
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40096
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40097
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40098
,80		
);





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40099
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40100
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40101
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40102
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40103
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40104
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40105
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40106
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40107
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40108
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40109
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40110
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40111
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40112
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40113
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40114
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40115
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40116
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40117
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40118
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40119
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40120
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40121
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40122
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40123
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40124
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40125
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40126
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40127
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40128
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40129
,80		
);




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40130
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40131
,80		
);



insert into MEP_PG_ROLES
(mep_id				
,pg_role_id		
)
values
(40132
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40133
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40134
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40135
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40136
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40137
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40138
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40139
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40140
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40141
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40142
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40143
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40144
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40145
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40146
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40147
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40148
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40149
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40150
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40151
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40152
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40153
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40154
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40155
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40156
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40157
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40158
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40159
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40160
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40161
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40162
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40163
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40164
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40165
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40166
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40167
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40168
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40169
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40170
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40171
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40172
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40173
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40174
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40175
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40176
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40177
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40178
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40179
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40180
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40181
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40182
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40183
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40184
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40185
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40186
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40187
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40188
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40189
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40190
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40191
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40192
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40193
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40194
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40195
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40196
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40197
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40198
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40199
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40200
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40201
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40202
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40203
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40204
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40205
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40206
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40207
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40208
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40209
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40210
,80		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40211
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40212
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40213
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40214
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40215
,80		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40216
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40217
,80		
);



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40218
,80		
);


/*********************************************/

/* Vice Presidents -- who make up the Parliament's Bureau  */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40004		
,50		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40005		
,50		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40006		
,50		
);

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40007		
,50		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40008		
,50		
);



/*********************************************/


/*******QUAESTORS **********************/


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40009		
,60		
);


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(40010		
,60		
);


/*********************************************/


COMMIT;  