--SET ECHO ON

/* These are the MEP_PG_ROLES for pg_id=60, i.e. Greens/EFA */


/*  SAMPLE DATA

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(990001		
,20		
)
;

*/

/*********************************************/

/* Chair */

/* PG_ROLE_ID = 20 */

/*********************************************/


/* CO-Chair */

/* PG_ROLE_ID = 30 */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60001		
,30		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60002		
,30		
)
;

/*********************************************/





/*  Members **********************************/
/* PG_ROLE_ID = 80 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60004		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60005		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60012		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60013		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60014		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60015		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60016		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60017		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60018		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60019		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60020		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60021		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60022		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60023		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60024		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60025		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60026		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60027		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60028		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60029		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60030		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60031		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60032		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60033		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60034		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60035		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60036		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60037		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60038		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60039		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60040		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60041		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60042		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60043		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60044		
,80		
)
;


/*********************************************/

/* Vice Presidents -- who make up the Parliament's Bureau  */
/* PG_ROLE_ID = 50 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60003		
,50		
)
;



/*********************************************/


/*******QUAESTORS **********************/
/* PG_ROLE_ID = 60 */

/*********************************************/



/*******VICE CHAIRMAN of the POLITICAL GROUP *********/
/* PG_ROLE_ID = 70 */




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60006		
,70		
)
;





insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60007		
,70		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60008		
,70		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60009		
,70		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60010		
,70		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(60011		
,70		
)
;



COMMIT;

