--SET ECHO ON

/* These are the MEP_PG_ROLES for pg_id=80, i.e. GUE/NGL */


/*  SAMPLE DATA

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(990001		
,20		
)
;


*/

/*********************************************/

/* Chair */

/* PG_ROLE_ID = 20 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80001		
,20		
)
;


/*********************************************/


/* CO-Chair */

/* PG_ROLE_ID = 30 */

/*********************************************/




/*  Members **********************************/
/* PG_ROLE_ID = 80 */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80003		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80004		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80005		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80006		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80007		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80008		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80009		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80010		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80011		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80012		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80013		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80014		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80015		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80016		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80017		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80018		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80019		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80020		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80021		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80022		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80023		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80024		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80025		
,80		
)
;



insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80026		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80027		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80028		
,80		
)
;




insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80029		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80030		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80031		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80032		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80033		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80034		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80035		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80036		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80037		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80038		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80039		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80040		
,80		
)
;



/*********************************************/

/* Vice Presidents -- who make up the Parliament's Bureau  */
/* PG_ROLE_ID = 50 */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80002		
,50		
)
;


/*********************************************/


/*******QUAESTORS **********************/
/* PG_ROLE_ID = 60 */

/*********************************************/


/*******VICE CHAIRMAN of the POLITICAL GROUP *********/
/* PG_ROLE_ID = 70 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(80041		
,70		
)
;




/*********************************************/

COMMIT;   

