
--SET ECHO ON

/* These are the MEP_PG_ROLES for pg_id=140, i.e. ALDE */


/*  SAMPLE DATA

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(990001		
,20		
)
;


*/

/*********************************************/

/* Chair */

/* PG_ROLE_ID = 20 */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140001		
,20		
)
;

/*********************************************/


/* CO-Chair */

/* PG_ROLE_ID = 30 */

/*********************************************/





/*  Members **********************************/
/* PG_ROLE_ID = 80 */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140006		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140007		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140008		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140009		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140010		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140011		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140012		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140013		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140014		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140015		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140016		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140017		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140018		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140019		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140020		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140021		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140022		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140023		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140024		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140025		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140026		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140027		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140028		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140029		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140030		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140031		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140032		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140033		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140034		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140035		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140036		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140037		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140038		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140039	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140040	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140041	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140042	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140043	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140044	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140045	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140046	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140047	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140048	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140049	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140050	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140051	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140052	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140053	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140054	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140055	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140056	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140057	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140058	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140059	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140060	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140061	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140062	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140063	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140064	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140065	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140066	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140067	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140068	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140069	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140070	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140071	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140072	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140073	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140074	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140075	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140076	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140077	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140078	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140079	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140080	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140081	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140082	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140083	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140084	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140085	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140086	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140087	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140088	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140089	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140090	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140091	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140092	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140093	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140094	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140095	
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140096	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140097	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140098	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140099	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140100	
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140101	
,80		
)
;


/*********************************************/

/* Vice Presidents -- who make up the Parliament's Bureau  */
/* PG_ROLE_ID = 50 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140002		
,50		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140003		
,50		
)
;



/* check this out ***********
insert into MEP_COMM_DELG_ROLES
(mep_id, role_id, comm_id, delg_id)
values
(140003,170,190,'');

*/


/*********************************************/


/*******QUAESTORS **********************/
/* PG_ROLE_ID = 60 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(140004		
,60		
)
;




/*********************************************/

COMMIT; 
