--SET ECHO ON

/* These are the MEP_PG_ROLES for pg_id=160, i.e. UEN */


/*  SAMPLE DATA

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(990001		
,20		
)
;


*/

/*********************************************/

/* Chair */

/* PG_ROLE_ID = 20 */

/*********************************************/


/* CO-Chair */

/* PG_ROLE_ID = 30 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160001		
,30		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160002		
,30		
)
;

/*********************************************/



/*  Members **********************************/
/* PG_ROLE_ID = 80 */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160004		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160005		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160006		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160007		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160008		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160009		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160010		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160011		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160013		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160014		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160016		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160017		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160018		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160019		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160020		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160021		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160022		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160023		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160024		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160025		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160026		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160027		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160028		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160029		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160030		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160031		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160032		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160033		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160034		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160035		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160036		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160037		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160038		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160039		
,80		
)
;


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160040		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160041		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160042		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160043		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160044		
,80		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160045		
,80		
)
;

/*********************************************/

/* Vice Presidents -- who make up the Parliament's Bureau  */
/* PG_ROLE_ID = 50 */

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160003		
,50		
)
;

/*********************************************/


/*******QUAESTORS **********************/
/* PG_ROLE_ID = 60 */

/*********************************************/



/*******VICE CHAIRMAN of the POLITICAL GROUP *********/
/* PG_ROLE_ID = 70 */


insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160012		
,70		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160015		
,70		
)
;

insert into MEP_PG_ROLES
(mep_id			
,pg_role_id		
)
values
(160046		
,70		
)
;


/*********************************************/

commit;  
